import styles from "../styles/index.module.css";
import { type NextPage } from "next";
import Head from "next/head";
import { api } from "../utils/api";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import { UserState } from "../reducers/user";

const Home: NextPage = () => {
  // Redirect to /login if not logged in
  const router = useRouter();
  useEffect(() => {
    if (!user.token) {
      router.push("/login");
    }
  }, []);

  const user = useSelector((state: { user: UserState }) => state.user.value);

  console.log(user);

  return (
    <>
      <Head>
        <title>TomTweet</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
          <h1 className={styles.title}>
            Tom<span className={styles.pinkSpan}>Tweet</span>
          </h1>
        </div>
      </main>
    </>
  );
};

export default Home;
